### ISSUE TITLE
Weblate no longer use github oauth?

### ISSUE THREAD

**Issue by h404bi** [MultiMC/MultiMC5-translate#4]
:question: Last time I used github oauth to log in, but this time I can't find the github oauth button.

**Comment by peterix** [comment]
I'm going to add them back to the new weblate server I'm setting up.

**Comment by peterix** [comment]
I am going to evaluate a different solution for translations (crowdin.com).

However, I'm adding this to the inftastructure tasks on workflowy, just in case that doesn't work out:
https://workflowy.com/s/2EyDMcp7CU

I am going to disable issues on this repository.
