### ISSUE TITLE
Cannot access weblate.robotbrain.info?

### ISSUE THREAD

**Issue by cqjjjzr** [MultiMC/MultiMC5-translate#5]
Hi there.
I have downloaded the .pom and translate it into my language, Chinese.
But when I try to access to weblate.robotbrain.info but it get "Timed out".
And how I install this .po to the MultiMC?
Thanks.
CharlieJiang

**Comment by peterix** [comment]
Hello, the server is down and has been for a while now. I'm working on setting up a new one, but that will take a few more days.

Ideally, fork the repository, add the file to your fork and create a pull request. Alternatively, you can just share the file. I can add it.

**Comment by peterix** [comment]
I'm not sure how to add translations. MultiMC, by default, rewrites them with files downloaded from the update server.

Maybe there should be some sensible mechanism for that.

Anyway, the best thing right now is to share the file itself. I'll add it to the repository and should have the server running in a few days.

**Comment by cqjjjzr** [comment]
@peterix OK, i found the Qt Linguist for it. Now I can view the translate progress on my MultiMC. After I complete my translate, I'll commit it.

**Comment by peterix** [comment]
The service now runs on http://translate.multimc.org
