### ISSUE TITLE
Make me translator on translate.multimc.org

### ISSUE THREAD

**Issue by sinanisler** [MultiMC/MultiMC5-translate#7]
I will finish Turkish translation. 
I have experience with this it would be fast if you give me translator permission.

**Comment by peterix** [comment]
You should be able to add suggestions for now. I'll have to find out how to set things up differently.

**Comment by sinanisler** [comment]
ok thanks :)

**Comment by sinanisler** [comment]
I made 80 translation you need to approve them 

please change my user level to translator so I dont need to bother you :)

Thanks.

**Comment by peterix** [comment]
I am sorry. Managing a translation server on top of everything else I do is a bit too much. I'm looking for an alternative solution that matches the MultiMC development model a bit better (crowdin.com). I'll try to preserve all the suggestions from the current server. It will take some time to set up though.

I don't see any unaccepted Turkish suggestions... you could have completed the translation ;)

Anyway, I am removing the issue tracking on this repository. If you need anything, use the main repository.
