### ISSUE TITLE
Text typo(not sure where it belongs)

### ISSUE THREAD

**Issue by kicKORhIT-16384-needSYDney** [MultiMC/MultiMC5-translate#82]
While translating, I found out (in Flame::UrlResolvingTask) that there are strings below:
-Failed to resove projectId as a number.
-Failed to resove fileId as a number.
These are clearly typos, but I don't know where they belong(no time to dive deep into the whole code, just a translator passing by.)

worth looking into, but not critical. #

**Comment by peterix** [comment]
Fixed in code
